ALICE = python main.py alice
BOB = python main.py bob
TABLE = python main.py table

default:
	@echo Hi, you can execute make bob in order to start the server.
	@echo Then open another terminal and execute make alice.

clean:
	rm -rf __pycache__

alice:
	${ALICE}

bob:
	${BOB}

table:
	${TABLE}
